Repository Club-Alpin-Lyon-Villeurbanne/plateforme-club-alpin, pull requests merged in 2025-09, with the labels that each got.

#1245 feat: wording surbooking
  legacy/scripts/operations/operations.user_join_manuel.php
  src/Controller/SortieController.php
Labels: prio élevée

#1237 fix: caractères accentués dans les noms de famille en majuscules
  legacy/app/fonctions.php
  legacy/includes/join_manual.php
  legacy/pages/adherents.php
  legacy/pages/admin-users.php
  legacy/pages/annuler-une-sortie.php
Labels: bug / fix, prio normale

#1230 fix: affichage des puces dans les pages libres
  assets/styles/styles.css
Labels: bug / fix, prio normale

#1243 fix: afficher la photo de l'utilisateur connecté
  templates/components/add-comment.html.twig
Labels: bug / fix, prio basse

#1263 fix(ffcam): correctement remonter ‘doit_renouveler’ (ne pas effacer date_adhesion, tolérance jusqu’au 31/12)
  src/Service/FfcamSynchronizer.php
Labels: bug / fix, prio urgente

#1259 fix: liste sorties : prio statuts
  templates/profil/sorties.html.twig
Labels: bug / fix, prio normale

#1240 feat: liens vers les applications de trajet
  assets/styles/styles.css
  public/img/gps/citymapper.png
  public/img/gps/geovelo.png
  public/img/gps/maps.png
  public/img/gps/waze.png
  src/Controller/SortieController.php
  templates/macros/cancel_block.html.twig
  templates/sortie/sortie.html.twig
Labels: prio basse

#1277 feat: ne pas notifier les VP des changements de responsabilités
  legacy/pages/adherents-droits.php
  legacy/pages/admin-users-droits.php
  src/Service/UserRightService.php
Labels: prio normale

#1258 feat: dépôt sortie : style bouton
  templates/sortie/formulaire.html.twig
Labels: prio basse

#1238 feat: liste globale des statuts des adhérents
  assets/styles/styles.css
  migrations/Version20250828140627.php
  src/Controller/UserController.php
  src/Repository/UserAttrRepository.php
  templates/base-wide.html.twig
  templates/header.html.twig
  templates/user/status-list.html.twig
Labels: prio normale

#1273 feat: rendre administrables certains contenus de pages fixes
  migrations/Version20250908132603.php
  templates/local_club/index.html.twig
  templates/minibus/index.html.twig
Labels: prio basse

#1278 feat: disclaimer images sur dépôt sortie
  assets/styles/styles.css
  config/services.yaml
  migrations/Version20250909122642.php
  src/Controller/SortieController.php
  src/Entity/Evt.php
  src/Form/ArticleType.php
  src/Form/EventType.php
  templates/article/edit.html.twig
  templates/sortie/formulaire.html.twig
Labels: prio élevée

#1297 fix: liens vers article pour éviter les erreurs d'inclusion legacy
  legacy/pages/accueil.php
  templates/email/transactional/notification-new-article.html.twig
  templates/sortie/sortie.html.twig
Labels: bug / fix, prio normale

#1300 fix: ignorer la casse dans la détection de doublon (import FFCAM)
  src/Repository/UserRepository.php
Labels: bug / fix, prio urgente

#1326 fix: pas d'empiètement avec sortie encore au brouillon
  legacy/scripts/fonctions.php
  src/Repository/EventParticipationRepository.php
Labels: bug / fix, prio élevée

#1327 fix: ne pas afficher les utilisateurs "supprimés"
  legacy/includes/fiche-profil.php
  legacy/pages/responsables.php
  legacy/pages/user-full.php
  src/Controller/UserController.php
  src/Entity/User.php
  src/Repository/UserAttrRepository.php
  src/Repository/UserRepository.php
  templates/sortie/sortie.html.twig
Labels: bug / fix, prio élevée

#1328 fix: saut de ligne
  templates/sortie/sortie.html.twig
Labels: bug / fix, prio basse

#1329 fix: slider page d'accueil
  legacy/pages/accueil.php
  public/js/accueil.js
Labels: bug / fix, prio normale

#1331 fix: alignement fiche de sortie
  templates/sortie/feuille-sortie.html.twig
Labels: bug / fix, prio normale

#1333 feat: retirer la civilité (affichage)
  legacy/app/fonctions.php
  legacy/includes/user/display_name.php
  legacy/pages/adherents-consulter.php
  legacy/pages/adherents-creer.php
  legacy/pages/adherents-modifier.php
  legacy/pages/adherents.php
  legacy/pages/admin-users.php
  legacy/pages/profil-infos.php
  legacy/scripts/operations/operations.user_contact.php
  legacy/scripts/operations/operations.user_create.php
  src/Controller/UserController.php
  templates/user/manual-add-select.html.twig
Labels: prio basse

#1330 fix: vérification contraintes d'unicité
  assets/styles/styles.css
  src/Controller/UserController.php
  templates/user/nomad-add.html.twig
Labels: bug / fix, prio urgente

#1336 fix: conserver les cases cochées
  src/Controller/ArticleController.php
  src/Controller/SortieController.php
  src/Form/ArticleType.php
  src/Form/EventType.php
Labels: bug / fix, prio basse

#1338 feat: changement de libellé
  docs/api.md
  src/Bridge/Twig/TwigExtension.php
  templates/sortie/sortie.html.twig
  templates/user/manual-add.html.twig
  translations/messages.fr.yaml
Labels: prio basse

#1348 fix: bulles-compteur de notifications dans le menu
  config/services.yaml
  src/Controller/EventManagementController.php
  src/Notifications.php
Labels: bug / fix, legacy => symfony, prio élevée

#1349 fix: retrait civilité
  src/Utils/ExcelExport.php
  templates/sortie/feuille-sortie.html.twig
Labels: bug / fix, prio basse

#1351 fix: restaurer fichier supprimé à tort
  public/js/faux-select.js
Labels: bug / fix, prio urgente
